# Generated by Django 4.1.5 on 2023-02-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_tax"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tax",
            options={"verbose_name_plural": "tax"},
        ),
    ]
